# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# enable cache
cache: pip

# Set the python version to 3.8
python: 3.8

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt

script:
  - python3 joke.py